from src.retrieval.rag_pipeline import DocumentChunk
from src.utils.ui import _build_final_answer


def test_build_final_answer_prefers_explanatory_sentences_over_toc_noise() -> None:
    unique = [
        (
            DocumentChunk(
                text=(
                    "Users will be able to create their exceptions for handling the errors. "
                    "Moreover , the user will see different use cases and control flow of Python exception hierarchy."
                ),
                doc_name="1008_python-for-everyone.pdf",
                page_num=9,
                chunk_id=0,
            ),
            0.79,
        ),
        (
            DocumentChunk(
                text=(
                    "When the error occurs, an exception is generated by Python that can be handled, "
                    "thus avoiding the program to crash."
                ),
                doc_name="1008_python-for-everyone.pdf",
                page_num=139,
                chunk_id=1,
            ),
            0.77,
        ),
        (
            DocumentChunk(
                text=(
                    "This abnormal termination can be handled explicitly using try-except blocks. "
                    "Thus, in default exception handling, the program will be terminated abnormally and will print exception information to the console."
                ),
                doc_name="python_book_test_notes.docx",
                page_num=14,
                chunk_id=2,
            ),
            0.72,
        ),
    ]

    panel = _build_final_answer("how exception handling works in python", unique)

    assert panel["summary_is_generated"] is True
    assert "try-except blocks" in panel["summary"].lower()
    assert "moreover" not in panel["summary"].lower()
    assert "the user will see" not in panel["summary"].lower()
